.TH GORELEASER-GENTOO-SMOKE 1 "2024-05-15" "0.1.0" "User Commands"
.SH NAME
goreleaser-gentoo-smoke \- Disposable GoReleaser Gentoo ebuild smoke test
.SH SYNOPSIS
.B goreleaser-gentoo-smoke
[\-version] [\-config <file>]
.SH DESCRIPTION
.B goreleaser-gentoo-smoke
is a minimal Go program used to test Gentoo ebuild generation in a GoReleaser pull request.
.SH OPTIONS
.TP
.B \-version
Print version and exit.
.TP
.B \-config <file>
Path to config file.
.SH AUTHOR
Written by arran4.
